// 14-jest/jest-react/src/components/Header/index.jsx
import { useState } from "react";
import "./index.css";

const Header = (props) => {
  const [inputValue, setInputValue] = useState("");
  const { add } = props;

  return (
    <div className="header">
      <span>ToDoList</span>
      <input
        className="header-input"
        data-test="input"
        value={inputValue}
        onChange={(e) => setInputValue(e.target.value)}
        onKeyUp={(e) => {
          if (e.keyCode === 13 && inputValue) {
            add?.(inputValue);
            setInputValue('')
          }
        }}
        placeholder="add ToDoItem"
      />
    </div>
  );
};

export default Header;

// 14-jest/jest-vue-ts/src/components/Header/index.tsx
import { defineComponent, ref } from "vue";
import { HeaderPropsDefine } from "../../utils/types";
import "./index.scss";

export default defineComponent({
  name: "Header",
  props: HeaderPropsDefine,
  setup(props) {
    const inputValue = ref<string>("");

    const addToDoItem = () => {
      props?.add(inputValue.value);
      inputValue.value = "";
    };

    return () => {
      return (
        <div class="header">
          <span>ToDoList</span>
          <input
            class="header-input"
            data-test="input"
            v-model={inputValue.value}
            onKeyup={(e: any) => {
              if (e.keyCode === 13 && inputValue) {
                addToDoItem();
              }
            }}
            placeholder="add ToDoItem"
          />
        </div>
      );
    };
  },
});
