// 05-Vue/vue2-jsx/src/App.jsx
import HelloWorld from './components/HelloWorld'
import logo from './assets/logo.png'
import './App.css'

const App = {
	name: 'App',
	components: {
		HelloWorld,
	},

	render() {
		return (
			<div id='app'>
				<img src={logo} alt='' />
				<HelloWorld msg='Welcome to Your Vue.js App' />
			</div>
		)
	},
}

export default App

// 05-Vue/vite-vue-ts/src/App.tsx
import { defineComponent } from "vue";
import logo from "./assets/logo.png";

export default defineComponent({
  name: "App",
  setup() {
    return () => (
      <>
        <img alt="Vue logo" src={logo} />
        <ul>
          <li>
            <router-link to="/">index</router-link>
          </li>
          <li>
            <router-link to="/watch">watch</router-link>
          </li>
          <li>
            <router-link to="/watchEffect">watchEffect</router-link>
          </li>
          <li>
            <router-link to="/chart">ChartDemo</router-link>
          </li>
        </ul>

        <router-view></router-view>
      </>
    );
  },
});
