// 14-jest/jest-vue-ts/src/App.tsx
import { defineComponent } from "vue";
// import HelloWorld from "./components/HelloWorld.vue";
import ToDoList from "./components/ToDoList/index";
import "./App.scss";

export default defineComponent({
  name: "App",
  setup() {
    return () => {
      return (
        <div id="app">
          {/* <img alt="Vue logo" src="./assets/logo.png" />
          <HelloWorld msg="Welcome to Your Vue.js + TypeScript App" /> */}
          <ToDoList />
        </div>
      );
    };
  },
});

// 14-jest/jest-vue/src/App.jsx
import ToDoList from "./components/ToDoList/index.jsx";
// import HellWorld from "./components/HelloWorld.vue";
import "./App.scss";

export default {
  name: "App",
  render() {
    return (
      <div id="app">
        {/* <HellWorld msg="1231" /> */}
        <ToDoList />
      </div>
    );
  },
};
