// 14-jest/jest-vue-ts/src/components/ToDoList/index.tsx
import { defineComponent, ref } from "vue";
import Header from "../Header/index";
import UnDoList from "../UnDoList/index";
import { UnDoListType } from "../../utils/types";

export default defineComponent({
  name: "ToDoList",
  setup() {
    const undoList = ref<UnDoListType[]>([]);

    const addUnDoItem = (inputValue: string) => {
      console.log(inputValue);
      undoList.value.push({
        status: "div",
        value: inputValue,
      });
      console.log(undoList.value);
    };

    const handleItemDelete = (index: number) => {
      undoList.value.splice(index, 1);
      console.log(undoList.value);
    };

    const changeStatus = (index: number) => {
      const newList: UnDoListType[] = [];
      undoList.value.forEach((item, itemIndex) => {
        newList.push({
          status: itemIndex === index ? "input" : "div",
          value: item.value,
        });
      });
      undoList.value = newList;
    };

    const resetStatus = () => {
      const newList: UnDoListType[] = [];
      undoList.value.forEach((item) => {
        newList.push({
          status: "div",
          value: item.value,
        });
      });
      undoList.value = newList;
    };

    const changeItemValue = ({ value, index }: any) => {
      undoList.value[index].value = value;
    };

    return () => {
      return (
        <div class="hello">
          <Header add={(e) => addUnDoItem(e)} />
          <UnDoList
            list={undoList.value}
            delete={handleItemDelete}
            status={changeStatus}
            reset={resetStatus}
            change={changeItemValue}
          />
        </div>
      );
    };
  },
});

// 14-jest/jest-react/src/components/ToDoList/index.jsx
import { useState } from "react";
import Header from "../Header/index.jsx";
import UnDoList from "../UnDoList/index.jsx";
import "./index.css";

const ToDoList = () => {
  const [undoList, setUndoList] = useState([]);

  const addUnDoItem = (value) => {
    setUndoList([
      ...undoList,
      {
        status: "div",
        value: value,
      },
    ]);
  };

  const handleItemDelete = (index) => {
    undoList.splice(index, 1);
    setUndoList([].concat(undoList));
  };

  const changeStatus = (index) => {
    const newList = [];
    undoList.forEach((item, itemIndex) => {
      newList.push({
        status: itemIndex === index ? "input" : "div",
        value: item.value,
      });
    });
    setUndoList(newList);
  };

  return (
    <div data-test="undoList" data-list={undoList}>
      <Header add={(value) => addUnDoItem(value)} />
      <UnDoList
        list={undoList}
        deleteItem={handleItemDelete}
        changeStatus={changeStatus}
      />
    </div>
  );
};

export default ToDoList;
