// 05-Vue/vue2-jsx/src/App.jsx
import HelloWorld from './components/HelloWorld'
import logo from './assets/logo.png'
import './App.css'

const App = {
	name: 'App',
	components: {
		HelloWorld,
	},

	render() {
		return (
			<div id='app'>
				<img src={logo} alt='' />
				<HelloWorld msg='Welcome to Your Vue.js App' />
			</div>
		)
	},
}

export default App

// 14-jest/jest-vue-ts/src/App.tsx
import { defineComponent } from "vue";
// import HelloWorld from "./components/HelloWorld.vue";
import ToDoList from "./components/ToDoList/index";
import "./App.scss";

export default defineComponent({
  name: "App",
  setup() {
    return () => {
      return (
        <div id="app">
          {/* <img alt="Vue logo" src="./assets/logo.png" />
          <HelloWorld msg="Welcome to Your Vue.js + TypeScript App" /> */}
          <ToDoList />
        </div>
      );
    };
  },
});
